# https://vektra.github.io/mockery/latest/configuration/
with-expecter: True
inpackage: True
dir: "{{.InterfaceDir}}"
all: True
packages:
  github.com/gkatanacio/paraphraser-api/internal/paraphrase:
    config:
      recursive: True
