service: paraphraser-api

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  deploymentMethod: direct
  deploymentBucket:
    name: ${env:AWS_DEPLOYMENT_BUCKET}
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        enableSimpleResponses: true
        functionName: authPassthrough # can be replaced with proper authorizer function

functions:
  authPassthrough:
    package:
      artifact: bin/auth-passthrough.zip
    handler: bootstrap

  paraphrase:
    package:
      artifact: bin/paraphrase.zip
    handler: bootstrap
    timeout: 20
    memorySize: 128
    events:
      - httpApi:
          method: post
          path: /paraphrase
          authorizer:
            name: customAuthorizer
    environment:
      PARAPHRASE_TIMEOUT: ${env:PARAPHRASE_TIMEOUT}
      CHATGPT_API_KEY: ${env:CHATGPT_API_KEY}
      CHATGPT_TEMPERATURE: ${env:CHATGPT_TEMPERATURE}
